version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ../WWW:/var/www/html
    depends_on:
      - db
    extra_hosts:
      - "tassonomie:127.0.0.1"

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: progetto_IGS
    ports:
      - "3306:3306"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
